"""GE Expectation Catalog — auto-generated from GE v0.18.22 (54 expectations)."""

GREAT_EXPECTATIONS_CATALOG = [
    {"type": "expect_column_distinct_values_to_be_in_set", "label": "枚举值", "category": "有效性",
     "params": {}},
    {"type": "expect_column_distinct_values_to_contain_set", "label": "必须包含值", "category": "有效性",
     "params": {}},
    {"type": "expect_column_distinct_values_to_equal_set", "label": "去重等于", "category": "有效性",
     "params": {}},
    {"type": "expect_column_kl_divergence_to_be_less_than", "label": "KL散度", "category": "分布",
     "params": {}},
    {"type": "expect_column_max_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_mean_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_median_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_min_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_most_common_value_to_be_in_set", "label": "枚举值", "category": "有效性",
     "params": {}},
    {"type": "expect_column_pair_values_a_to_be_greater_than_b", "label": "列A>列B", "category": "跨字段",
     "params": {}},
    {"type": "expect_column_pair_values_to_be_equal", "label": "列A=列B", "category": "跨字段",
     "params": {}},
    {"type": "expect_column_pair_values_to_be_in_set", "label": "枚举值", "category": "有效性",
     "params": {}},
    {"type": "expect_column_proportion_of_unique_values_to_be_between", "label": "唯一值占比", "category": "唯一性",
     "params": {}},
    {"type": "expect_column_quantile_values_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_stdev_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_sum_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_to_exist", "label": "列存在", "category": "完整性",
     "params": {}},
    {"type": "expect_column_unique_value_count_to_be_between", "label": "唯一值数量", "category": "唯一性",
     "params": {}},
    {"type": "expect_column_value_lengths_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_value_lengths_to_equal", "label": "字符串固定长度", "category": "格式",
     "params": {}},
    {"type": "expect_column_value_z_scores_to_be_less_than", "label": "Z分数", "category": "数值",
     "params": {}},
    {"type": "expect_column_values_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_column_values_to_be_dateutil_parseable", "label": "日期可解析", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_be_decreasing", "label": "严格递减", "category": "趋势",
     "params": {}},
    {"type": "expect_column_values_to_be_in_set", "label": "枚举值", "category": "有效性",
     "params": {}},
    {"type": "expect_column_values_to_be_in_type_list", "label": "类型列表", "category": "有效性",
     "params": {}},
    {"type": "expect_column_values_to_be_increasing", "label": "严格递增", "category": "趋势",
     "params": {}},
    {"type": "expect_column_values_to_be_json_parseable", "label": "JSON可解析", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_be_null", "label": "全部为空", "category": "完整性",
     "params": {}},
    {"type": "expect_column_values_to_be_of_type", "label": "类型检查", "category": "有效性",
     "params": {}},
    {"type": "expect_column_values_to_be_unique", "label": "唯一值", "category": "唯一性",
     "params": {}},
    {"type": "expect_column_values_to_match_json_schema", "label": "JSON Schema", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_match_like_pattern", "label": "LIKE匹配", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_match_like_pattern_list", "label": "LIKE匹配", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_match_regex", "label": "正则匹配", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_match_regex_list", "label": "正则匹配", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_match_strftime_format", "label": "日期格式", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_not_be_in_set", "label": "枚举值", "category": "有效性",
     "params": {}},
    {"type": "expect_column_values_to_not_be_null", "label": "非空检查", "category": "完整性",
     "params": {}},
    {"type": "expect_column_values_to_not_match_like_pattern", "label": "LIKE匹配", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_not_match_like_pattern_list", "label": "LIKE匹配", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_not_match_regex", "label": "正则匹配", "category": "格式",
     "params": {}},
    {"type": "expect_column_values_to_not_match_regex_list", "label": "正则匹配", "category": "格式",
     "params": {}},
    {"type": "expect_compound_columns_to_be_unique", "label": "唯一值", "category": "唯一性",
     "params": {}},
    {"type": "expect_multicolumn_sum_to_equal", "label": "总和", "category": "数值",
     "params": {}},
    {"type": "expect_select_column_values_to_be_unique_within_record", "label": "唯一值", "category": "唯一性",
     "params": {}},
    {"type": "expect_table_column_count_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_table_column_count_to_equal", "label": "列数", "category": "表级",
     "params": {}},
    {"type": "expect_table_columns_to_match_ordered_list", "label": "表结构匹配", "category": "表级",
     "params": {}},
    {"type": "expect_table_columns_to_match_set", "label": "表结构匹配", "category": "表级",
     "params": {}},
    {"type": "expect_table_row_count_to_be_between", "label": "数值范围", "category": "数值",
     "params": {}},
    {"type": "expect_table_row_count_to_equal", "label": "行数", "category": "表级",
     "params": {}},
    {"type": "expect_table_row_count_to_equal_other_table", "label": "行数", "category": "表级",
     "params": {}},
    {"type": "unexpected_rows_expectation", "label": "异常行检测", "category": "异常",
     "params": {}},
]

def get_expectation_catalog() -> list[dict]:
    return GREAT_EXPECTATIONS_CATALOG

def get_expectation_by_type(expectation_type: str) -> dict | None:
    for exp in GREAT_EXPECTATIONS_CATALOG:
        if exp["type"] == expectation_type:
            return exp
    return None
