-- InsightForge demo schema (Oracle Free — runs as APP_USER insight)

CREATE TABLE product_lines (
    code VARCHAR2(32) PRIMARY KEY,
    name VARCHAR2(128) NOT NULL,
    region VARCHAR2(32) NOT NULL
);

COMMENT ON TABLE product_lines IS '产品线维度';

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(64) NOT NULL,
    city VARCHAR2(64),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE users IS '用户维度';

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_line_code VARCHAR2(32) NOT NULL,
    name VARCHAR2(128) NOT NULL,
    price NUMBER(12, 2) NOT NULL,
    CONSTRAINT fk_products_line FOREIGN KEY (product_line_code) REFERENCES product_lines(code)
);

COMMENT ON TABLE products IS '商品维度';

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    status VARCHAR2(16) NOT NULL,
    amount NUMBER(14, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE orders IS '订单事实表';
COMMENT ON COLUMN orders.amount IS '订单成交金额 GMV';

CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    line_amount NUMBER(14, 2) NOT NULL,
    CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES products(id)
);

INSERT INTO product_lines (code, name, region) VALUES ('east', '华东产品线', '华东');
INSERT INTO product_lines (code, name, region) VALUES ('south', '华南产品线', '华南');

INSERT INTO users (id, name, city, created_at) VALUES (1, '张三', '上海', TIMESTAMP '2026-01-05 10:00:00');
INSERT INTO users (id, name, city, created_at) VALUES (2, '李四', '杭州', TIMESTAMP '2026-01-08 11:00:00');
INSERT INTO users (id, name, city, created_at) VALUES (3, '王五', '深圳', TIMESTAMP '2026-01-10 09:30:00');

INSERT INTO products (id, product_line_code, name, price) VALUES (1, 'east', '华东旗舰款', 1999);
INSERT INTO products (id, product_line_code, name, price) VALUES (2, 'east', '华东标准款', 899);
INSERT INTO products (id, product_line_code, name, price) VALUES (3, 'south', '华南热销款', 1299);

INSERT INTO orders (id, user_id, status, amount, created_at) VALUES (101, 1, 'paid', 1999, TIMESTAMP '2026-05-01 10:00:00');
INSERT INTO orders (id, user_id, status, amount, created_at) VALUES (102, 1, 'paid', 899, TIMESTAMP '2026-05-02 14:00:00');
INSERT INTO orders (id, user_id, status, amount, created_at) VALUES (103, 2, 'paid', 1299, TIMESTAMP '2026-05-03 09:00:00');
INSERT INTO orders (id, user_id, status, amount, created_at) VALUES (104, 3, 'pending', 1299, TIMESTAMP '2026-05-10 16:00:00');
INSERT INTO orders (id, user_id, status, amount, created_at) VALUES (105, 2, 'refunded', 899, TIMESTAMP '2026-05-11 11:00:00');

INSERT INTO order_items (id, order_id, product_id, quantity, line_amount) VALUES (1, 101, 1, 1, 1999);
INSERT INTO order_items (id, order_id, product_id, quantity, line_amount) VALUES (2, 102, 2, 1, 899);
INSERT INTO order_items (id, order_id, product_id, quantity, line_amount) VALUES (3, 103, 3, 1, 1299);
INSERT INTO order_items (id, order_id, product_id, quantity, line_amount) VALUES (4, 104, 3, 1, 1299);
INSERT INTO order_items (id, order_id, product_id, quantity, line_amount) VALUES (5, 105, 2, 1, 899);

COMMIT;
