"""港航业务术语预置 catalog（非完整 ontology）。"""
from __future__ import annotations

PORT_GLOSSARY_SEED: list[dict] = [
    {"term": "TEU", "definition": "Twenty-foot Equivalent Unit，标准箱换算单位，用于衡量集装箱吞吐量。", "domain": "container", "aliases": ["标准箱", "标箱"]},
    {"term": "泊位", "definition": "港口供船舶停靠、装卸作业的固定水工设施。", "domain": "berth", "aliases": ["berth"]},
    {"term": "在港时长", "definition": "船舶从抵港到离港的总停留时间，含等待、靠泊、作业等环节。", "domain": "vessel", "aliases": ["在港时间", "port stay"]},
    {"term": "吞吐量", "definition": "一定时期内港口完成的货物或集装箱装卸总量。", "domain": "port", "aliases": ["throughput"]},
    {"term": "箱量", "definition": "集装箱装卸数量，通常以 TEU 或自然箱计量。", "domain": "container", "aliases": ["集装箱量"]},
    {"term": "靠泊", "definition": "船舶系缆停靠码头进行装卸作业的状态。", "domain": "vessel", "aliases": ["berthing"]},
    {"term": "离港", "definition": "船舶完成在港作业后解缆离开港口。", "domain": "vessel", "aliases": ["departure"]},
    {"term": "抵港", "definition": "船舶到达港口锚地或引航登轮的时间点。", "domain": "vessel", "aliases": ["arrival"]},
    {"term": "堆场", "definition": "港口存放集装箱或货物的陆域堆存区域。", "domain": "yard", "aliases": ["yard", "CY"]},
    {"term": "闸口", "definition": "集疏运车辆进出港区堆场的检查与放行通道。", "domain": "gate", "aliases": ["gate"]},
    {"term": "重箱", "definition": "装有货物的集装箱。", "domain": "container", "aliases": ["laden"]},
    {"term": "空箱", "definition": "未装货物的集装箱，用于调运或待装。", "domain": "container", "aliases": ["empty container"]},
    {"term": "班轮", "definition": "按固定航线、船期和挂港计划运营的集装箱船舶。", "domain": "vessel", "aliases": ["liner"]},
    {"term": "挂靠港", "definition": "班轮航线中计划停靠的港口。", "domain": "port", "aliases": ["port of call"]},
    {"term": "装卸效率", "definition": "单位时间内完成的装卸量，如箱/小时。", "domain": "operation", "aliases": ["productivity"]},
    {"term": "等泊时间", "definition": "船舶抵港至实际靠泊之间的等待时长。", "domain": "vessel", "aliases": ["waiting time"]},
    {"term": "引航", "definition": "引航员登轮协助船舶安全进出港口的作业。", "domain": "operation", "aliases": ["pilotage"]},
    {"term": "拖轮", "definition": "协助大型船舶靠离泊的辅助船舶。", "domain": "operation", "aliases": ["tugboat"]},
    {"term": "舱单", "definition": "列明船舶所载货物明细的单证。", "domain": "document", "aliases": ["manifest"]},
    {"term": "提单", "definition": "承运人签发的货物收据和运输合同凭证。", "domain": "document", "aliases": ["B/L", "bill of lading"]},
    {"term": "报关", "definition": "进出口货物向海关申报并接受监管的程序。", "domain": "customs", "aliases": ["customs declaration"]},
    {"term": "查验", "definition": "海关或监管部门对货物进行开箱或机检的过程。", "domain": "customs", "aliases": ["inspection"]},
    {"term": "疏港", "definition": "将港口堆存货物运出港区至腹地或下一节点的过程。", "domain": "operation", "aliases": ["cargo evacuation"]},
    {"term": "集港", "definition": "将腹地货物运送至港口堆场或码头待装船的过程。", "domain": "operation", "aliases": ["cargo gathering"]},
    {"term": "冷藏箱", "definition": "带制冷设备的集装箱，用于运输温控货物。", "domain": "container", "aliases": ["reefer"]},
    {"term": "危险品箱", "definition": "装载危险货物的集装箱，需特殊堆存与作业规范。", "domain": "container", "aliases": ["DG container"]},
    {"term": "翻捣箱", "definition": "堆场内为调整箱位而进行的移箱作业。", "domain": "yard", "aliases": ["restow"]},
    {"term": "桥吊", "definition": "码头前沿用于船舶装卸的岸边集装箱起重机。", "domain": "equipment", "aliases": ["QC", "quay crane"]},
    {"term": "场桥", "definition": "堆场内用于集装箱水平搬运和堆垛的轮胎式起重机。", "domain": "equipment", "aliases": ["RTG", "RMG"]},
    {"term": "内贸", "definition": "国内贸易货物，不涉及跨境海关监管。", "domain": "trade", "aliases": ["domestic trade"]},
    {"term": "外贸", "definition": "进出口贸易货物，需经海关监管。", "domain": "trade", "aliases": ["foreign trade"]},
]
